CORPUS = 'corpus'
ANNOTATIONS = 'annotations'
PROCESSED_CORPUS = 'processed_corpus'

LIVE_IN = 'Live_In'
WORK_FOR = 'Work_For'

ID = 'ID'
FORM = 'FORM'
LEMMA = 'LEMMA'
POSTAG = 'POSTAG'
NETAG = 'NETAG'
HEAD = 'HEAD'
DEPREL = 'DEPREL'
ENTIBO = 'ENTIBO'
ENTTYPE = 'ENTTYPE'

FIELDS_H = [ID, FORM, LEMMA, POSTAG, NETAG, HEAD, DEPREL, ENTIBO, ENTTYPE]
